# Generated by Django 5.0.6 on 2024-06-24 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mobile', models.CharField(max_length=50, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('MapLink', models.TextField(null=True)),
                ('GithubLink', models.CharField(max_length=150, null=True)),
                ('FacebookLink', models.CharField(max_length=150, null=True)),
                ('YoutubeLink', models.CharField(max_length=150, null=True)),
                ('TwitterLink', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='EmergencyContact',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='FatherName',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='MotherName',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='PermanentAddress',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='PresentAddress',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='Religion',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='EmergencyContact',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='FatherName',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='Mobile',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='MotherName',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='PermanentAddress',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='PresentAddress',
        ),
        migrations.RemoveField(
            model_name='teachermodel',
            name='Religion',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='FacebookLink',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='GithubLink',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='LinkedInLink',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='FacebookLink',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='GithubLink',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='JoinDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='LinkedInLink',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='imsusermodel',
            name='UserType',
            field=models.CharField(choices=[('Authority', 'Authority'), ('Student', 'Student'), ('Teacher', 'Teacher'), ('Staff', 'Staff')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PersonalInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FatherName', models.CharField(max_length=100, null=True)),
                ('MotherName', models.CharField(max_length=100, null=True)),
                ('Religion', models.CharField(max_length=100, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100, null=True)),
                ('Mobile', models.CharField(max_length=100, null=True)),
                ('EmergencyContact', models.CharField(max_length=100, null=True)),
                ('PresentAddress', models.CharField(max_length=100, null=True)),
                ('PermanentAddress', models.CharField(max_length=100, null=True)),
                ('Imsuser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, null=True)),
                ('Salary', models.CharField(max_length=150, null=True)),
                ('PaymentDate', models.DateField(null=True)),
                ('Imsuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffName', models.CharField(max_length=150, null=True)),
                ('EmployID', models.CharField(max_length=150, null=True)),
                ('StaffDesignation', models.CharField(max_length=150, null=True)),
                ('JoinDate', models.DateField(auto_now_add=True, null=True)),
                ('Imsuser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
