# Generated by Django 5.0.6 on 2024-06-26 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0002_contactmodel_remove_studentmodel_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='StudentID',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='AdmissionDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='AdmittedCourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseFee', models.CharField(max_length=150, null=True)),
                ('Payment', models.CharField(max_length=150, null=True)),
                ('Due', models.CharField(max_length=150, null=True)),
                ('AdmissionDate', models.DateField(auto_now_add=True, null=True)),
                ('AssignTeacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IMSapp.teachermodel')),
                ('CourseName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IMSapp.courseinfomodel')),
                ('Courseuser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('LearningBatch', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='IMSapp.batchinfomodel')),
            ],
        ),
    ]
