# Generated by Django 5.0.6 on 2024-06-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0002_batchinfomodel_coursename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchinfomodel',
            name='CourseName',
        ),
        migrations.AddField(
            model_name='batchinfomodel',
            name='CourseName',
            field=models.ManyToManyField(to='IMSapp.coursecategorymodel'),
        ),
    ]
