# Generated by Django 5.0.6 on 2024-06-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0003_studentmodel_studentid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactModel',
            new_name='WebsiteContactModel',
        ),
    ]
