# Generated by Django 5.0.6 on 2024-06-27 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0003_remove_batchinfomodel_coursename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchinfomodel',
            name='CourseName',
        ),
        migrations.AddField(
            model_name='batchinfomodel',
            name='CourseName',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coursenameinfo', to='IMSapp.courseinfomodel'),
        ),
    ]
