# Generated by Django 5.0.6 on 2024-06-26 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0004_rename_contactmodel_websitecontactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontactmodel',
            name='Imsuser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
