# Generated by Django 5.0.6 on 2024-06-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0004_remove_batchinfomodel_coursename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admittedcoursemodel',
            name='AssignTeacher',
        ),
        migrations.RemoveField(
            model_name='admittedcoursemodel',
            name='CourseName',
        ),
        migrations.AlterField(
            model_name='batchinfomodel',
            name='Status',
            field=models.CharField(choices=[('On-Going', 'On-Going'), ('Upcomming', 'Upcomming'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
    ]
