# Generated by Django 5.0.6 on 2024-06-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0005_websitecontactmodel_imsuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachermodel',
            name='Imsuser',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
