# Generated by Django 5.0.6 on 2024-06-27 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0007_alter_admittedcoursemodel_learningbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchinfomodel',
            name='CourseName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coursenameinfo', to='IMSapp.courseinfomodel'),
        ),
    ]
