# Generated by Django 5.0.6 on 2024-06-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0007_alter_teachermodel_imsuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfomodel',
            old_name='ClassDurationHour',
            new_name='ClassDuration',
        ),
        migrations.RenameField(
            model_name='courseinfomodel',
            old_name='AboutCourse',
            new_name='CourseCurrriculum',
        ),
        migrations.RenameField(
            model_name='courseinfomodel',
            old_name='ClassDurationMinute',
            new_name='Sologan',
        ),
        migrations.RenameField(
            model_name='courseinfomodel',
            old_name='CourseTopics',
            new_name='TotalProject',
        ),
        migrations.RemoveField(
            model_name='batchinfomodel',
            name='Batchuser',
        ),
        migrations.AddField(
            model_name='courseinfomodel',
            name='CourseFor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseinfomodel',
            name='CourseOverview',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseinfomodel',
            name='IntroVideo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='courseinfomodel',
            name='JobPositions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='courseinfomodel',
            name='Software',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfomodel',
            name='CourseName',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
