# Generated by Django 5.0.6 on 2024-06-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0008_rename_classdurationhour_courseinfomodel_classduration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfomodel',
            name='Lecture',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfomodel',
            name='ClassDuration',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
