# Generated by Django 5.0.6 on 2024-06-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0008_alter_batchinfomodel_coursename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admittedcoursemodel',
            name='Courseuser',
        ),
        migrations.AddField(
            model_name='admittedcoursemodel',
            name='StudentID',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
