# Generated by Django 5.0.6 on 2024-06-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0009_courseinfomodel_lecture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfomodel',
            name='ClassDuration',
            field=models.IntegerField(null=True),
        ),
    ]
