# Generated by Django 5.0.6 on 2024-06-27 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0009_remove_admittedcoursemodel_courseuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittedcoursemodel',
            name='LearningBatch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batchinfo', to='IMSapp.batchinfomodel'),
        ),
        migrations.AlterField(
            model_name='salarymodel',
            name='Imsuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salaryinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
