# Generated by Django 5.0.6 on 2024-06-28 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0010_alter_admittedcoursemodel_learningbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittedcoursemodel',
            name='Courseuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admittedcourseinfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
