# Generated by Django 5.0.6 on 2024-06-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0011_admittedcoursemodel_courseuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfomodel',
            name='Password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
