# Generated by Django 5.0.6 on 2024-06-28 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0012_personalinfomodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittedcoursemodel',
            name='LearningBatch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batchinfo', to='IMSapp.batchinfomodel'),
        ),
    ]
