# Generated by Django 5.0.6 on 2024-06-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0014_alter_admittedcoursemodel_learningbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmodel',
            name='StaffPhoto',
            field=models.ImageField(null=True, upload_to='media/staffphoto'),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='TeacherPhoto',
            field=models.ImageField(null=True, upload_to='media/teacherphoto'),
        ),
    ]
