# Generated by Django 5.0.6 on 2024-06-28 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0015_staffmodel_staffphoto_teachermodel_teacherphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittedcoursemodel',
            name='CourseName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courseinfo', to='IMSapp.courseinfomodel'),
        ),
    ]
