# Generated by Django 5.0.6 on 2024-06-29 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0016_admittedcoursemodel_coursename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.TextField(null=True)),
                ('CourseName', models.CharField(max_length=100, null=True)),
                ('ReviewDate', models.DateField(null=True)),
                ('Imsuser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
