# Generated by Django 5.0.6 on 2024-06-29 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0017_reviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='admittedcoursemodel',
            name='Studentuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studetinfo', to='IMSapp.studentmodel'),
        ),
    ]
