# Generated by Django 5.0.6 on 2024-06-29 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0018_admittedcoursemodel_studentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='BatchNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewbatchinfo', to='IMSapp.batchinfomodel'),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='Status',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='CourseName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewcourseinfo', to='IMSapp.admittedcoursemodel'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='Imsuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewinfo', to='IMSapp.studentmodel'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='ReviewDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
