# Generated by Django 5.0.6 on 2024-06-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0019_reviewmodel_batchno_reviewmodel_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewmodel',
            name='BatchNo',
        ),
        migrations.RemoveField(
            model_name='reviewmodel',
            name='CourseName',
        ),
    ]
