# Generated by Django 5.0.6 on 2024-06-29 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0020_remove_reviewmodel_batchno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='CourseName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewcourseinfo', to='IMSapp.courseinfomodel'),
        ),
    ]
