# Generated by Django 5.0.6 on 2024-06-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0021_reviewmodel_coursename'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingStudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BatchNo', models.CharField(max_length=100, null=True)),
                ('CourseName', models.CharField(max_length=100, null=True)),
                ('StudentName', models.CharField(max_length=100, null=True)),
                ('StudentPhoto', models.ImageField(null=True, upload_to='media/pendingstudentPhoto')),
                ('AdmissionDate', models.DateField(auto_now_add=True, null=True)),
                ('EducationalQualification', models.CharField(max_length=100, null=True)),
                ('FatherName', models.CharField(max_length=100, null=True)),
                ('MotherName', models.CharField(max_length=100, null=True)),
                ('Religion', models.CharField(max_length=100, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100, null=True)),
                ('Mobile', models.CharField(max_length=100, null=True)),
                ('EmergencyContact', models.CharField(max_length=100, null=True)),
                ('PresentAddress', models.CharField(max_length=100, null=True)),
                ('PermanentAddress', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
