# Generated by Django 5.0.6 on 2024-07-01 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0022_pendingstudentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherBatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherbatch', to='IMSapp.batchinfomodel')),
                ('teacheruser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacherbatchinfo', to='IMSapp.teachermodel')),
            ],
        ),
    ]
