# Generated by Django 5.0.6 on 2024-07-01 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0024_alter_teacherbatchmodel_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=20, null=True)),
                ('Date', models.DateField(null=True)),
                ('BatchNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IMSapp.batchinfomodel')),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IMSapp.studentmodel')),
            ],
        ),
    ]
