# Generated by Django 5.0.6 on 2024-07-01 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0025_studentattendancemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendance', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Pending', 'Pending')], max_length=20, null=True)),
                ('Date', models.DateField(null=True)),
                ('date_time', models.DateTimeField(null=True)),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='IMSapp.teachermodel')),
            ],
        ),
    ]
