# Generated by Django 5.0.6 on 2024-07-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0026_teacherattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
