# Generated by Django 5.0.6 on 2024-07-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0028_alter_teacherattendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='Attendance',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
