# Generated by Django 5.0.6 on 2024-07-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMSapp', '0029_alter_teacherattendance_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='Attendance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Pending', 'Pending')], max_length=20, null=True),
        ),
    ]
